import { expect, test } from '@playwright/test';

for (const viewport of [{ width: 1440, height: 900 }, { width: 390, height: 760 }]) {
  test(`continuous conversation preserves reading and task controls at ${viewport.width}px`, async ({ page }) => {
    await page.setViewportSize(viewport);
    const errors: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('/mobile-workspace-visual.html?long-chat&task&running-task');
    if (viewport.width < 1024) await page.locator('.workspace-mobile-nav').getByRole('button', { name: '问答', exact: true }).click();
    const rail = page.locator('.right-rail');
    const transcript = rail.locator('.transcript');
    const input = rail.locator('textarea[data-workspace-input="agent"]');
    const height = (await rail.boundingBox())!.height;
    expect((await transcript.boundingBox())!.height / height).toBeGreaterThan(.7);
    expect((await input.boundingBox())!.height).toBeLessThanOrEqual(46);
    await expect(rail.locator('.agent-compose-row > button')).toHaveCount(1);
    await expect(rail.locator('.agent-compose-row > button')).toHaveText('停止');
    await expect(rail.locator('.goal-card')).toHaveCount(0);
    await expect(rail.locator('.task-summary-toggle')).toContainText('正在执行');
    await transcript.evaluate(el => { el.scrollTop = 120; el.dispatchEvent(new Event('scroll')); });
    const before = await transcript.boundingBox();
    await rail.locator('.task-summary-toggle').click();
    await expect(rail.locator('.goal-card')).toContainText('交付全书主线演示');
    await expect(rail.locator('.goal-card')).not.toContainText('等待继续');
    await expect(rail.locator('.goal-card')).not.toContainText('页面交付待确认');
    expect((await transcript.boundingBox())!.height).toBeCloseTo(before!.height, 0);
    await page.keyboard.press('Escape');
    await expect(rail.locator('.goal-card')).toHaveCount(0);
    expect(await transcript.evaluate(el => el.scrollTop)).toBeCloseTo(120, 0);
    await input.fill('第一行\n第二行\n第三行\n第四行\n第五行\n第六行');
    await expect.poll(async () => (await input.boundingBox())!.height).toBeGreaterThan(44);
    expect((await input.boundingBox())!.height).toBeLessThanOrEqual(120);
    await input.press('Control+Enter');
    await expect(page.locator('.fixture-send-count')).toHaveAttribute('data-count', '0');
    await rail.getByRole('button', { name: '收起输入', exact: true }).click();
    await expect(input).toHaveValue('第一行\n第二行\n第三行\n第四行\n第五行\n第六行');
    await expect.poll(async () => (await input.boundingBox())!.height).toBeLessThanOrEqual(46);
    expect(await transcript.evaluate(el => el.scrollTop)).toBeCloseTo(120, 0);
    await rail.locator('.stop-agent').click();
    await expect(rail.locator('.task-summary-toggle')).toContainText('本次生成已停止');
    await expect(rail.locator('.agent-compose-row > button')).toHaveText('发送');
    await rail.locator('.task-summary-toggle').click();
    await rail.getByRole('button', { name: '继续任务', exact: true }).click();
    await expect(rail.locator('.task-summary-toggle')).toContainText('正在执行');
    await rail.locator('.stop-agent').click();
    await rail.locator('.task-summary-toggle').click();
    await rail.getByRole('button', { name: '补充要求', exact: true }).click();
    await expect(rail.locator('.goal-target')).toContainText('全书的主线');
    await rail.getByRole('button', { name: '取消补充任务', exact: true }).click();
    await input.press('Escape');
    await rail.locator('.task-summary-toggle').click();
    await rail.getByRole('button', { name: '结束任务', exact: true }).click();
    await expect(rail.locator('.task-summary-toggle')).toHaveCount(0);
    await expect(input).toHaveValue('第一行\n第二行\n第三行\n第四行\n第五行\n第六行');
    expect(await rail.evaluate(el => el.scrollWidth - el.clientWidth)).toBeLessThanOrEqual(1);
    await input.focus();
    await input.press('Control+Enter');
    await expect(page.locator('.fixture-send-count')).toHaveAttribute('data-count', '1');
    await expect(input).toHaveValue('');
    await input.fill('连续输入第一行\n第二行\n第三行\n第四行\n第五行');
    await expect.poll(async () => (await input.boundingBox())!.height).toBeGreaterThan(44);
    await input.press('Escape');
    expect(errors).toEqual([]);
    await page.screenshot({ path: `../../tmp/reader-space-20261009/actual-${viewport.width}.png` });
  });
}

test('wide browser keeps a narrow assistant toolbar on one row with discoverable tools', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('/mobile-workspace-visual.html?long-chat');
  const rail = page.locator('.right-rail');
  expect((await rail.boundingBox())!.width).toBeLessThan(520);
  expect((await rail.locator('.rail-toolbar').boundingBox())!.height).toBeLessThanOrEqual(54);
  await expect(rail.locator('.secondary-tabs')).toBeHidden();
  await expect(rail.locator('.chat-secondary-actions')).toBeHidden();
  await rail.getByRole('button', { name: '阅读工具', exact: true }).click();
  await rail.getByRole('tab', { name: '公式', exact: true }).click();
  await expect(rail.locator('#reader-panel-formula')).toBeVisible();
  await rail.getByRole('tab', { name: '问答', exact: true }).click();
  await rail.getByRole('button', { name: '问答操作', exact: true }).click();
  await rail.getByRole('button', { name: '本书历史', exact: false }).click();
  await expect(page.locator('.history-dialog')).toBeVisible();
  await page.getByRole('button', { name: '关闭历史', exact: true }).click();
  await expect(rail.locator('textarea')).toHaveValue('未发送草稿');
});
