ALTER TABLE run_admissions ADD COLUMN cancel_requested INTEGER NOT NULL DEFAULT 0;
ALTER TABLE run_admissions ADD COLUMN key_closed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE run_admissions ADD COLUMN unsaved INTEGER NOT NULL DEFAULT 0;
